import { createClient } from "https://esm.sh/@supabase/supabase-js@2.117.3.117.3";
const ORIGIN="https://zeletas.netlify.app";const cors={"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"authorization,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
function key(){const r=Deno.env.get("SUPABASE_SECRET_KEYS");if(r)try{return JSON.parse(r).default}catch{}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!}
function pub(){const r=Deno.env.get("SUPABASE_PUBLISHABLE_KEYS");if(r)try{return JSON.parse(r).default}catch{}return Deno.env.get("SUPABASE_ANON_KEY")!}
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"Content-Type":"application/json"}});
async function hash(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,"0")).join("")}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);const auth=req.headers.get("Authorization");if(!auth?.startsWith("Bearer "))return json({error:"Unauthorized"},401);const client=createClient(Deno.env.get("SUPABASE_URL")!,pub(),{global:{headers:{Authorization:auth}}});const {data:{user},error}=await client.auth.getUser();const aal=(await client.auth.mfa.getAuthenticatorAssuranceLevel()).data;if(aal?.nextLevel==="aal2"&&aal.currentLevel!=="aal2")return Response.json({error:"MFA_REQUIRED"},{status:403,headers:cors});if(error||!user)return json({error:"Unauthorized"},401);const body=await req.json().catch(()=>null);const type=String(body?.targetType||""),id=String(body?.targetId||""),reason=String(body?.reason||"").trim();if(!["listing","product","store","profile","message"].includes(type)||!id||reason.length<3||reason.length>500)return json({error:"Invalid report"},400);const admin=createClient(Deno.env.get("SUPABASE_URL")!,key());
let targetExists=false;
if(type==="listing"){const q=await admin.from("listings").select("id").eq("id",id).maybeSingle();targetExists=Boolean(q.data)}
if(type==="product"){const q=await admin.from("products").select("id").eq("id",id).maybeSingle();targetExists=Boolean(q.data)}
if(type==="store"){const q=await admin.from("stores").select("id").eq("id",id).maybeSingle();targetExists=Boolean(q.data)}
if(type==="profile"){const q=await admin.from("profiles").select("user_id").eq("user_id",id).maybeSingle();targetExists=Boolean(q.data)}
if(type==="message"){
 const q=await admin.from("messages").select("id,conversation_id").eq("id",id).maybeSingle();
 if(q.data){const member=await admin.from("conversation_members").select("conversation_id").eq("conversation_id",q.data.conversation_id).eq("user_id",user.id).maybeSingle();targetExists=Boolean(member.data)}
}
if(!targetExists)return json({error:"Contenido no disponible para reportar"},404);
const k=await hash(user.id);const rl=await admin.from("moderation_rate_limits").select("last_report_at").eq("key_hash",k).maybeSingle();if(rl.data&&Date.now()-new Date(rl.data.last_report_at).getTime()<300000)return json({error:"Rate limited"},429);await admin.from("moderation_rate_limits").upsert({key_hash:k,last_report_at:new Date().toISOString()});const c=await admin.from("moderation_cases").insert({target_type:type,target_id:id,reporter_id:user.id,reason,status:"open"}).select("id").single();if(c.error)return json({error:"Could not create report"},500);return json({id:c.data.id})});