import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
function adminKey(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(raw){try{return JSON.parse(raw).default}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!}
async function hmacHex(keyText:string,data:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(keyText),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const out=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(data));return Array.from(new Uint8Array(out)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function sameHex(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function valid(body:string,header:string){const secret=Deno.env.get("STRIPE_WEBHOOK_SECRET");if(!secret)return false;const parts=header.split(",");const ts=parts.find(x=>x.startsWith("t="))?.slice(2);const signatures=parts.filter(x=>x.startsWith("v1=")).map(x=>x.slice(3));if(!ts||!signatures.length||!/^[0-9]+$/.test(ts))return false;const timestamp=Number(ts);if(!Number.isFinite(timestamp)||Math.abs(Math.floor(Date.now()/1000)-timestamp)>300)return false;const expected=await hmacHex(secret,ts+"."+body);return signatures.some(sig=>sameHex(sig,expected))}
async function stripePost(path:string,params:URLSearchParams){const secret=Deno.env.get("STRIPE_SECRET_KEY");if(!secret)return {ok:false};const r=await fetch("https://api.stripe.com/v1/"+path,{method:"POST",headers:{"Authorization":"Bearer "+secret,"Content-Type":"application/x-www-form-urlencoded"},body:params});return {ok:r.ok,data:await r.json()}}
Deno.serve(async req=>{if(req.method!=="POST")return new Response("Method not allowed",{status:405});const body=await req.text();if(!(await valid(body,req.headers.get("stripe-signature")||"")))return new Response("Invalid signature",{status:400});let event:any;try{event=JSON.parse(body)}catch{return new Response("Invalid event",{status:400})}
const admin=createClient(Deno.env.get("SUPABASE_URL")!,adminKey());const object=event.data?.object||{};const orderId=object.metadata?.order_id||object.client_reference_id||null;
await admin.from("payment_events").upsert({external_event_id:event.id,event_type:event.type,order_id:orderId,payload:event},{onConflict:"external_event_id",ignoreDuplicates:true});
if(event.type==="account.updated"){const accountId=object.id;const ready=Boolean(object.details_submitted&&object.charges_enabled&&object.payouts_enabled);await admin.from("stores").update({stripe_onboarding_complete:ready}).eq("stripe_account_id",accountId);return Response.json({received:true})}
if(orderId&&event.type==="checkout.session.completed"){const order=await admin.from("orders").select("id,buyer_id,status,stripe_payment_intent_id").eq("id",orderId).maybeSingle();if(order.data&&["paid","processing","shipped","completed","refunded","cancelled"].includes(order.data.status))return Response.json({received:true});
const stock=await admin.rpc("fulfill_order_stock",{target_order_id:orderId});
if(stock.error){await admin.from("orders").update({status:"refund_pending"}).eq("id",orderId);if(object.payment_intent){const p=new URLSearchParams();p.set("payment_intent",object.payment_intent);const refund=await stripePost("refunds",p);if(refund.ok){await admin.from("orders").update({status:"cancelled"}).eq("id",orderId);if(order.data?.buyer_id)await admin.from("notifications").insert({user_id:order.data.buyer_id,type:"payment",title:"Pedido cancelado",body:"El pago se ha revertido porque no había stock suficiente.",data:{order_id:orderId}})}}return Response.json({received:true})}
await admin.from("orders").update({status:"paid",stripe_payment_intent_id:object.payment_intent||null}).eq("id",orderId);if(order.data?.buyer_id)await admin.from("notifications").insert({user_id:order.data.buyer_id,type:"payment",title:"Pago confirmado",body:"Tu pedido ha sido pagado correctamente.",data:{order_id:orderId}})}
if(orderId&&event.type==="payment_intent.payment_failed"){await admin.from("orders").update({status:"cancelled"}).eq("id",orderId)}
if(orderId&&event.type==="checkout.session.expired"){await admin.from("orders").update({status:"cancelled"}).eq("id",orderId)}
if(orderId&&event.type==="charge.refunded"){await admin.from("orders").update({status:"refunded"}).eq("id",orderId)}
if(orderId&&event.type==="charge.refund.updated"&&object.status==="failed"){await admin.from("orders").update({status:"refund_pending"}).eq("id",orderId)}
if(orderId&&event.type==="order.refund.retry"){const o=await admin.from("orders").select("buyer_id,stripe_payment_intent_id,status").eq("id",orderId).maybeSingle();if(o.data?.status==="refund_pending"&&o.data.stripe_payment_intent_id){const p=new URLSearchParams();p.set("payment_intent",o.data.stripe_payment_intent_id);const refund=await stripePost("refunds",p);if(refund.ok){await admin.from("orders").update({status:"cancelled"}).eq("id",orderId)}}}
if(orderId&&["charge.refunded","refund.created"].includes(event.type)){await admin.from("orders").update({status:"refunded"}).eq("id",orderId);const o=await admin.from("orders").select("buyer_id").eq("id",orderId).maybeSingle();if(o.data?.buyer_id)await admin.from("notifications").insert({user_id:o.data.buyer_id,type:"refund",title:"Pago reembolsado",body:"Tu pago ha sido reembolsado.",data:{order_id:orderId}})}
return Response.json({received:true})});